# Generated by Django 2.0.3 on 2018-11-28 22:23

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('deckString', models.CharField(max_length=200)),
                ('deckClass', models.CharField(max_length=20)),
                ('maxMatchIdChecked', models.IntegerField()),
                ('isBulkTest', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Generous',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deckShare.Deck')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blizzTag', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('token', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('lastUpdateCollection', models.CharField(blank=True, max_length=100)),
                ('time', models.FloatField(default=0)),
                ('collection', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('latestActivity', models.IntegerField(blank=True, null=True)),
                ('generous', models.ManyToManyField(blank=True, to='deckShare.Generous')),
                ('matches', models.ManyToManyField(blank=True, to='deckShare.Match')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('wishList', models.ManyToManyField(blank=True, to='deckShare.Deck')),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deckShare.Profile'),
        ),
        migrations.AddField(
            model_name='match',
            name='partnerDecks',
            field=models.ManyToManyField(related_name='partnerDecks', to='deckShare.Deck'),
        ),
        migrations.AddField(
            model_name='match',
            name='playerDecks',
            field=models.ManyToManyField(related_name='playerDecks', to='deckShare.Deck'),
        ),
        migrations.AddField(
            model_name='deck',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deckShare.Profile'),
        ),
    ]
