# Generated by Django 2.0.3 on 2018-10-25 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deckShare', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deck',
            old_name='Hero',
            new_name='deckClass',
        ),
    ]
