# Generated by Django 2.0.3 on 2018-11-29 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deckShare', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='partner',
        ),
        migrations.RemoveField(
            model_name='match',
            name='partnerDecks',
        ),
        migrations.RemoveField(
            model_name='match',
            name='playerDecks',
        ),
        migrations.AlterField(
            model_name='profile',
            name='matches',
            field=models.ManyToManyField(blank=True, related_name='_profile_matches_+', to='deckShare.Profile'),
        ),
        migrations.DeleteModel(
            name='Match',
        ),
    ]
