# Generated by Django 2.0.3 on 2018-10-30 16:58

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('deckShare', '0002_auto_20181025_2217'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blizzTag', models.CharField(blank=True, max_length=100)),
                ('token', models.CharField(blank=True, max_length=100)),
                ('refreshtoken', models.CharField(blank=True, max_length=100)),
                ('collection', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='player',
            name='matches',
        ),
        migrations.RemoveField(
            model_name='player',
            name='wishList',
        ),
        migrations.RemoveField(
            model_name='match',
            name='player1',
        ),
        migrations.RemoveField(
            model_name='match',
            name='player2',
        ),
        migrations.DeleteModel(
            name='Player',
        ),
        migrations.AddField(
            model_name='profile',
            name='matches',
            field=models.ManyToManyField(blank=True, to='deckShare.Match'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profile',
            name='wishList',
            field=models.ManyToManyField(blank=True, to='deckShare.Deck'),
        ),
        migrations.AddField(
            model_name='match',
            name='user1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='player1', to='deckShare.Profile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='user2',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='player2', to='deckShare.Profile'),
            preserve_default=False,
        ),
    ]
