# Generated by Django 2.0.3 on 2018-12-01 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deckShare', '0002_auto_20181129_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='awaitingResponse',
            field=models.ManyToManyField(blank=True, related_name='_profile_awaitingResponse_+', to='deckShare.Profile'),
        ),
        migrations.AddField(
            model_name='profile',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='_profile_friends_+', to='deckShare.Profile'),
        ),
        migrations.AddField(
            model_name='profile',
            name='offeredFriendship',
            field=models.ManyToManyField(blank=True, related_name='_profile_offeredFriendship_+', to='deckShare.Profile'),
        ),
    ]
