# Generated by Django 2.0.3 on 2018-10-30 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deckShare', '0003_auto_20181030_1658'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='refreshtoken',
            new_name='refreshToken',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='token',
        ),
        migrations.AlterField(
            model_name='match',
            name='user1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user1', to='deckShare.Profile'),
        ),
        migrations.AlterField(
            model_name='match',
            name='user2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user2', to='deckShare.Profile'),
        ),
    ]
