# Generated by Django 2.0.3 on 2018-10-30 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deckShare', '0004_auto_20181030_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
