# Generated by Django 2.0.3 on 2018-12-01 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deckShare', '0004_auto_20181201_1653'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='awaitingResponse',
        ),
        migrations.AddField(
            model_name='profile',
            name='awaitingResponse',
            field=models.ManyToManyField(blank=True, related_name='friendAwaiting', to='deckShare.Profile'),
        ),
        migrations.RemoveField(
            model_name='profile',
            name='offeredFriendship',
        ),
        migrations.AddField(
            model_name='profile',
            name='offeredFriendship',
            field=models.ManyToManyField(blank=True, related_name='friendOffering', to='deckShare.Profile'),
        ),
    ]
