# Generated by Django 2.0.3 on 2018-10-30 19:43

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deckShare', '0005_profile_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='token',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
