# Generated by Django 2.0.8 on 2018-12-15 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deckShare', '0006_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='timeStamp',
        ),
    ]
