# Generated by Django 2.0.3 on 2018-10-30 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deckShare', '0006_profile_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='refreshToken',
        ),
        migrations.AddField(
            model_name='profile',
            name='lastUpdateCollection',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
