# Generated by Django 2.0.8 on 2018-12-15 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deckShare', '0007_remove_message_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='timeOfMessage',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
