# Generated by Django 2.0.3 on 2018-10-31 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deckShare', '0007_auto_20181030_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='time',
            field=models.FloatField(blank=True, default=1.0),
            preserve_default=False,
        ),
    ]
