# Generated by Django 2.0.8 on 2018-12-17 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deckShare', '0008_message_timeofmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='channelHash',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
