# Generated by Django 2.0.3 on 2018-11-02 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deckShare', '0009_auto_20181102_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='time',
            field=models.FloatField(default=0),
        ),
    ]
