# Generated by Django 2.0.3 on 2018-11-02 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deckShare', '0010_auto_20181102_2139'),
    ]

    operations = [
        migrations.CreateModel(
            name='Generous',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deckShare.Deck')),
            ],
        ),
        migrations.AlterField(
            model_name='match',
            name='deck1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deck1', to='deckShare.Deck'),
        ),
        migrations.AlterField(
            model_name='match',
            name='deck2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deck2', to='deckShare.Deck'),
        ),
        migrations.AddField(
            model_name='profile',
            name='generous',
            field=models.ManyToManyField(blank=True, to='deckShare.Generous'),
        ),
    ]
