# Generated by Django 2.0.3 on 2018-11-03 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deckShare', '0011_auto_20181102_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='MaxMatchIdChecked',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
