# Generated by Django 2.0.3 on 2018-11-03 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deckShare', '0012_deck_maxmatchidchecked'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deck',
            old_name='MaxMatchIdChecked',
            new_name='maxMatchIdChecked',
        ),
    ]
