# Generated by Django 2.0.3 on 2018-11-06 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deckShare', '0013_auto_20181103_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='latestActivity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
