# Generated by Django 2.0.3 on 2018-11-13 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deckShare', '0014_profile_latestactivity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='latestActivity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
