# Generated by Django 2.0.3 on 2018-11-14 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deckShare', '0015_auto_20181113_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='isBulkTest',
            field=models.BooleanField(default=False),
        ),
    ]
